### ISSUE TITLE
Watch recursion

### ISSUE THREAD

**Issue by trsh** [webpack/watchpack#53] opened 2017-06-27 13:25 UTC
So recently I got problems in webpack, where the watcher is spamming "compile" events for files that are updated before watching starts.  The rabbit hole was deep, but led me to watchpack. 

So:

1. So at some point `doInitialScan `is processed in `DirectoryWatcher`.
2. This, at least for files, runs `setFileTime`
3. As the `inital `flag is set, this `this.files[filePath] = [initial ? Math.min(now, mtime) : now, mtime];` mostly equals to `this.files[filePath] = [mtime, mtime];`, because the file mtime will be smaller the time now (in case I edited file before running watcher).
4. Next at some point it gets to `process.nextTick` and `var ts = data[0] === data[1] ? data[0] + FS_ACCURACY : data[0];` and `if(ts >= startTime)watcher.emit("change", data[1]);`
5. As this `data[0] === data[1]` is `true` (check point 3), `FS_ACCURACY` is added. So `ts` is bigger than `startTime` (delivered from webpack compiler it's `self.startTime = Date.now();`).
6. So for aprox 10 seconds (FS_ACCURACY = 10000 milis) it'ss spamming compile events, until the date `now ` reaches file mtime+10 secs.

This doesn't feel right :/

**Comment by trsh** [comment] 2017-07-18 07:54
Any comments?

**Comment by AlexGalays** [comment] 2017-07-25 14:47
Same as https://github.com/webpack/watchpack/issues/25
?

**Comment by trsh** [comment] 2017-07-25 14:53
@AlexGalays yes

**Comment by evilebottnawi** [comment] 2018-02-08 16:09
@trsh duplicate https://github.com/webpack/watchpack/issues/53?

**Comment by YurySolovyov** [comment] 2018-02-08 16:26
Adjusting concurrency seems like a crutch, race condition like that should never happen by design.

If that means things will go slower, it is fine, cause spamming like that confusing and slowing developers anyway.

Please, dear core team, do **not** trade speed for correctness and robustness.

**Comment by sokra** [comment] 2019-07-10 18:08
closing as it's a duplicate

**Closed by sokra** 2019-07-10 18:08 UTC
